Repository rayyaw/flash-patcher, pull requests merged in 2024-01, with the labels that each got.

#62 Fix bug with multiple injection in the same file
  .github/common-setup.sh
  README.md
  build/Makefile
  flash_patcher/inject/single_injection.py
  test/inject/test_single_injection.py
Labels: bug

#70 Improve code coverage checking
  .github/workflows/unittest.yml
  build/Makefile
Labels: bug, code improvements

#69 Run python scripts in the correct directory
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  flash_patcher/parse/visitor/stage_visitor.py
  flash_patcher/util/external_cmd.py
  requirements.txt
  test/parse/visitor/test_stage_visitor.py
  test/testdata/Stage1.stage
  test/testdata/mod/scripts/frame_1/DoAction1.as
  test/testdata/mod/scripts/frame_1/DoAction2.as
  test/util/test_external_cmd.py
Labels: bug

#72 Implement replace all
  README.md
  flash_patcher/antlr/PatchfileParser.g4
  flash_patcher/parse/visitor/patch_visitor.py
  test/parse/visitor/test_patch_visitor.py
  test/testdata/Patch4.patch
Labels: feature request

#74 Implement add at content
  README.md
  build/pyproject.toml
  flash_patcher/antlr/PatchfileLexer.g4
  flash_patcher/antlr/PatchfileParser.g4
  flash_patcher/inject/find_content.py
  flash_patcher/inject/location/parser_injection_location.py
  test/inject/location/test_parser_injection_location.py
  test/inject/test_find_content.py
  test/parse/visitor/test_patch_visitor.py
  test/testdata/Patch1.patch
  test/testdata/Patch2.patch
Labels: feature request

#75 Update exception handling
  flash_patcher/exception/error_manager.py
  flash_patcher/util/file_io.py
  test/util/test_file_io.py
Labels: code improvements
